/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author marcf
 */
public class VentanaCalculadora extends javax.swing.JFrame {
   
    //variables
   double operando1 = 0; //variable de instancia que almacenará el operando1
   String operacion = ""; 
   double operando2 = 0;
   double entero= 0;
    
    
    
    
    /**
     * Creates new form VentanaCalculadora
     */
    public VentanaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonMas = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        botonMenos = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        botonPor = new javax.swing.JButton();
        botonSinNada = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        botonDividir = new javax.swing.JButton();
        historia = new javax.swing.JLabel();
        botonEnteros = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantalla.setBackground(new java.awt.Color(0, 0, 0));
        pantalla.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        pantalla.setForeground(new java.awt.Color(0, 204, 0));
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.setText("0");
        pantalla.setOpaque(true);
        getContentPane().add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 373, -1));

        boton7.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        boton7.setText("7");
        boton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton7MousePressed(evt);
            }
        });
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        getContentPane().add(boton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 64, 64));

        boton8.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        boton8.setText("8");
        boton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton8MousePressed(evt);
            }
        });
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        getContentPane().add(boton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 112, 64, 64));

        boton9.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        boton9.setText("9");
        boton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton9MousePressed(evt);
            }
        });
        getContentPane().add(boton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 112, 64, 64));

        botonMas.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        botonMas.setText("+");
        botonMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonMasMousePressed(evt);
            }
        });
        botonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMasActionPerformed(evt);
            }
        });
        getContentPane().add(botonMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 112, 64, 64));

        boton4.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        boton4.setText("4");
        boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton4MousePressed(evt);
            }
        });
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        getContentPane().add(boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 194, 64, 64));

        boton5.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        boton5.setText("5");
        boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton5MousePressed(evt);
            }
        });
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        getContentPane().add(boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 194, 64, 64));

        boton6.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        boton6.setText("6");
        boton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton6MousePressed(evt);
            }
        });
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        getContentPane().add(boton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 194, 64, 64));

        botonMenos.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        botonMenos.setText("-");
        botonMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonMenosMousePressed(evt);
            }
        });
        botonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenosActionPerformed(evt);
            }
        });
        getContentPane().add(botonMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 194, 64, 64));

        boton1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        boton1.setText("1");
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton1MousePressed(evt);
            }
        });
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 276, 64, 64));

        boton2.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        boton2.setText("2");
        boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton2MousePressed(evt);
            }
        });
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        getContentPane().add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 276, 64, 64));

        boton3.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        boton3.setText("3");
        boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton3MousePressed(evt);
            }
        });
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        getContentPane().add(boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 276, 64, 64));

        botonPor.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        botonPor.setText("*");
        botonPor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonPorMousePressed(evt);
            }
        });
        botonPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPorActionPerformed(evt);
            }
        });
        getContentPane().add(botonPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 276, 64, 64));

        botonSinNada.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        botonSinNada.setText("C");
        botonSinNada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonSinNadaMousePressed(evt);
            }
        });
        botonSinNada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSinNadaActionPerformed(evt);
            }
        });
        getContentPane().add(botonSinNada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 433, 64, 64));

        boton0.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        boton0.setText("0");
        boton0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton0MousePressed(evt);
            }
        });
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        getContentPane().add(boton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 358, 64, 64));

        botonIgual.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonIgualMousePressed(evt);
            }
        });
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        getContentPane().add(botonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 433, 64, 64));

        botonDividir.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        botonDividir.setText("/");
        botonDividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonDividirMousePressed(evt);
            }
        });
        botonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDividirActionPerformed(evt);
            }
        });
        getContentPane().add(botonDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 358, 64, 64));

        historia.setBackground(new java.awt.Color(0, 0, 0));
        historia.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        historia.setForeground(new java.awt.Color(0, 204, 0));
        historia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        historia.setOpaque(true);
        getContentPane().add(historia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 373, 32));

        botonEnteros.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        botonEnteros.setText("+ -");
        botonEnteros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonEnterosMousePressed(evt);
            }
        });
        botonEnteros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnterosActionPerformed(evt);
            }
        });
        getContentPane().add(botonEnteros, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 433, 64, 64));

        botonPunto.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        botonPunto.setText(".");
        botonPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonPuntoMousePressed(evt);
            }
        });
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(botonPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 433, 64, 64));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton8ActionPerformed

    private void botonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMasActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton6ActionPerformed

    private void botonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMenosActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton3ActionPerformed

    private void botonPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPorActionPerformed

    private void botonSinNadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSinNadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSinNadaActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        
    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDividirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonDividirActionPerformed

    
    private void colorGrisTodo(){
        //pone todos los botones gris 
        boton0.setBackground(Color.lightGray);
         boton1.setBackground(Color.lightGray);
         boton2.setBackground(Color.lightGray);
         boton3.setBackground(Color.lightGray);
         boton4.setBackground(Color.lightGray);
         boton5.setBackground(Color.lightGray);
         boton6.setBackground(Color.lightGray);
         boton7.setBackground(Color.lightGray);
         boton8.setBackground(Color.lightGray);
         boton9.setBackground(Color.lightGray);
         botonMas.setBackground(Color.lightGray);
         botonMenos.setBackground(Color.lightGray);
         botonPor.setBackground(Color.lightGray);
         botonDividir.setBackground(Color.lightGray);
         botonEnteros.setBackground(Color.lightGray);
         botonPunto.setBackground(Color.lightGray);
    
}
    private void colorGrisNumeros(){
       // para poner todos los botones con numeros y el de decimal y de enteros grises
         boton0.setBackground(Color.lightGray);
         boton1.setBackground(Color.lightGray);
         boton2.setBackground(Color.lightGray);
         boton3.setBackground(Color.lightGray);
         boton4.setBackground(Color.lightGray);
         boton5.setBackground(Color.lightGray);
         boton6.setBackground(Color.lightGray);
         boton7.setBackground(Color.lightGray);
         boton8.setBackground(Color.lightGray);
         boton9.setBackground(Color.lightGray);
         botonEnteros.setBackground(Color.lightGray);
         botonPunto.setBackground(Color.lightGray);
}
     private void realizaOperacion(){  
     // le aporta un valor a operando1 
     //solo si hay numero disitinto de 0 en la screen
     //envia a la pantalla un 0
     // resetea los colores de los botones
     
        if (pantalla.getText()!="0"){
        operando1 = Double.valueOf(pantalla.getText());
        pantalla.setText("0");
        }
        
      
         
         colorGrisNumeros();
        
    }
    
    
    
    private void metodoHistoria (){
       //pone en la pantalla de abajo los calculos que se estan haciendo
        operando1 = Double.valueOf(operando1);
        operando2 = Double.valueOf(operando2);
        
        if(operando1 == 0){
            historia.setText(pantalla.getText() + operacion);
        }
        
        if(operando2 == 0 && operando1 !=0){
            historia.setText(operando1 + operacion+ pantalla.getText() );
        }
        if (operando1 !=0 && operando2 != 0){
        historia.setText(operando1 + operacion + operando2);
        }
        // este es el caso en que se de a un numero y acto seguido al botonIgual
        if (operando1==0 && operando2 !=0){
            historia.setText(pantalla.getText());
            
        }
    }
    
    private void cambiaTextoEnPantalla(JButton boton){
        //si no hay ceros sigue escribiendo los numeros que el usuario quiera 
        //en la pantalla
        //si hay cero, lo quita y pone los numeros que el usuario quiera en la 
        //pantalla
          if (pantalla.getText() !="0" ){
        pantalla.setText(pantalla.getText() + boton.getText());
        
        }
        else{
            pantalla.setText(boton.getText());
        
        }
    }
    
    
     private void borrarNumero(JButton color){
         //resetea tanto las variables, los colores y las pantallas
         
         operando1 = 0;
         operando2 = 0;
         operacion="";
         pantalla.setText("0");
         historia.setText("");
         colorGrisTodo();
     }
    
    
    
    
    
    
    private void boton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton7MousePressed
      cambiaTextoEnPantalla(boton7);
      metodoHistoria();
      boton7.setBackground(Color.red);
    }//GEN-LAST:event_boton7MousePressed

    private void boton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton8MousePressed
        cambiaTextoEnPantalla(boton8);
        metodoHistoria();
        boton8.setBackground(Color.red);
    }//GEN-LAST:event_boton8MousePressed

    private void boton9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton9MousePressed
        cambiaTextoEnPantalla(boton9);
        metodoHistoria();
        boton9.setBackground(Color.red);
    }//GEN-LAST:event_boton9MousePressed

    private void boton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MousePressed
        cambiaTextoEnPantalla(boton4);
        metodoHistoria();
        boton4.setBackground(Color.red);
    }//GEN-LAST:event_boton4MousePressed

    private void boton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton5MousePressed
        cambiaTextoEnPantalla(boton5);
        metodoHistoria();
        boton5.setBackground(Color.red);
    }//GEN-LAST:event_boton5MousePressed

    private void boton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton6MousePressed
        cambiaTextoEnPantalla(boton6);
        metodoHistoria();
        boton6.setBackground(Color.red);
    }//GEN-LAST:event_boton6MousePressed

    private void boton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MousePressed
        cambiaTextoEnPantalla(boton1);
       metodoHistoria();
       boton1.setBackground(Color.red);
    }//GEN-LAST:event_boton1MousePressed

    private void boton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MousePressed
        cambiaTextoEnPantalla(boton2);
        metodoHistoria();
        boton2.setBackground(Color.red);
    }//GEN-LAST:event_boton2MousePressed

    private void boton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3MousePressed
        cambiaTextoEnPantalla(boton3);
        metodoHistoria();
        boton3.setBackground(Color.red);
    }//GEN-LAST:event_boton3MousePressed

    private void boton0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton0MousePressed
        cambiaTextoEnPantalla(boton0);
        metodoHistoria();
        boton0.setBackground(Color.red);
    }//GEN-LAST:event_boton0MousePressed

   
    
    
    private void botonMasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMasMousePressed
        botonMas.setBackground(Color.red);
        realizaOperacion();
        operacion = "+";
         
         botonMenos.setBackground(Color.lightGray);
         botonPor.setBackground(Color.lightGray);
         botonDividir.setBackground(Color.lightGray);

    }//GEN-LAST:event_botonMasMousePressed

    private void botonIgualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIgualMousePressed

        operando2 = Double.valueOf(pantalla.getText());
           //he guardado el simbolo de la opercaion en una variable de instancia
           // asi que el compilador puede comprobar que simbolo se ha pulsado y
           // hacer la operacion conveniente
        metodoHistoria();
        if (operacion == ("+")){
            
         operando1 = operando1 + operando2;  
         pantalla.setText(String.valueOf(operando1));
        
        }
         if (operacion.equals("-")){
            
         operando1 = operando1 - operando2;
         pantalla.setText(String.valueOf(operando1));
        }
          if (operacion.equals("*")){
            
         operando1 = operando1 * operando2;
         pantalla.setText(String.valueOf(operando1));
        }
           if (operacion.equals("/")){
            if (operando2 <1){
                pantalla.setText("Eres tonto?");
            } else{
         operando1 = operando1 / operando2; 
         pantalla.setText(String.valueOf(operando1));
            }
        }
        
        // para resetear el color de los botones
        
         colorGrisTodo();
         
    }//GEN-LAST:event_botonIgualMousePressed

    private void botonMenosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenosMousePressed
       botonMenos.setBackground(Color.red);
        realizaOperacion(); 
       operacion = "-";
         botonMas.setBackground(Color.lightGray);
         botonPor.setBackground(Color.lightGray);
         botonDividir.setBackground(Color.lightGray);
    }//GEN-LAST:event_botonMenosMousePressed

    private void botonPorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPorMousePressed
        botonPor.setBackground(Color.red);
        realizaOperacion();
        operacion = "*";
         botonMas.setBackground(Color.lightGray);
         botonMenos.setBackground(Color.lightGray);
         botonDividir.setBackground(Color.lightGray);
    }//GEN-LAST:event_botonPorMousePressed

    private void botonDividirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDividirMousePressed
        botonDividir.setBackground(Color.red);
        realizaOperacion();
        operacion = "/";
         botonMas.setBackground(Color.lightGray);
         botonMenos.setBackground(Color.lightGray);
         botonPor.setBackground(Color.lightGray);
    }//GEN-LAST:event_botonDividirMousePressed
    
    private void botonSinNadaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSinNadaMousePressed
        borrarNumero(boton0);
        
    }//GEN-LAST:event_botonSinNadaMousePressed

    private void botonEnterosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEnterosMousePressed
       
       //botonEnteros.setBackground(Color.red);
      
       entero = Double.valueOf(pantalla.getText());
       entero = entero * -1;
       //IMPORTANTE PARA PASAR UN DOUBLE A STRING!!!!!
       pantalla.setText(String.valueOf(entero));
       
       
       
       // }
    }//GEN-LAST:event_botonEnterosMousePressed

    private void botonEnterosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnterosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEnterosActionPerformed

    private void botonPuntoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPuntoMousePressed
        botonPunto.setBackground(Color.red);
        pantalla.setText(pantalla.getText() + botonPunto.getText());
    }//GEN-LAST:event_botonPuntoMousePressed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPuntoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonDividir;
    private javax.swing.JButton botonEnteros;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMas;
    private javax.swing.JButton botonMenos;
    private javax.swing.JButton botonPor;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonSinNada;
    private javax.swing.JLabel historia;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
